# Generated by Django 6.0.5 on 2026-05-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('option1', models.CharField(max_length=255)),
                ('option2', models.CharField(max_length=255)),
                ('option3', models.CharField(max_length=255)),
                ('option4', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(choices=[('Option1', 'Option 1'), ('Option2', 'Option 2'), ('Option3', 'Option 3'), ('Option4', 'Option 4')], help_text='Select the correct option (Option1, Option2, Option3, or Option4)', max_length=10)),
            ],
        ),
    ]
